<?php 

namespace Yaf\Model\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * BaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends EntityRepository
{
    protected function filterParams($where)
    {
        $ret = [];
        foreach ($where as $key => $val)
        {
            if ($val !== "unuse")
            {
                $ret[$key] =  $val;
            }
        }
        return $ret;
    }
    
    protected function object2arr($object)
    {
    	$item = [];
    	$methods = get_class_methods($object);
    	foreach ($methods as $method)
    	{
    		if ($pos = strpos($method, 'get') !== false)
    		{
    			$key = lcfirst(substr($method, 3));
    			$item[$key] = $object->$method();
    		}
    	}
    	return $item;
    }
}