<?php

namespace Yaf\Model\Repository;

use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use Yaf\Model\Entities\Category;
/**
 * BlogCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends BaseRepository
{
	public function getCategoryTree($pid = 0, $render, $expand)
	{
		$categories = $this->findAll();
		{
			$tree = array(); //格式化的树
			$tmpMap = array();  //临时扁平数据

			foreach ($categories as $key => $item) {
				$categories[$key] = $item = $this->object2arr($item);
				$tmp = [
						"expand" => $expand,
						"title" => $item['name'],
						"info" => $item['info'],
						"cid" => $item['id']
				];
				if (!$render)
				{
					$tmp['checked'] = false;
					$tmp['selected'] = false;
				}

				$tmpMap[$item['id']] = $tmp;
			}
			foreach ($categories as $item) {
				if (isset($tmpMap[$item['pid']])) {
					$tmpMap[$item['pid']]['children'][] = &$tmpMap[$item['id']];
				} else if ($pid == 0 ){
					$tree[] = &$tmpMap[$item['id']];
				}
				if ($pid != 0 && $item['id'] == $pid)
				{
					$tree = &$tmpMap[$item['id']];
				}
			}
			unset($tmpMap);
		}
		return $tree;
	}

	public function deleteCategoryTree($cid)
	{
			$childs = $this->getCategoryChilds_cascad($cid);
			$childs[] = ['id' => $cid];
			foreach ($childs as $child)
			{
				$ac = $this->getEntityManager()->getRepository('Yaf\Model\Entities\GoodCategory')
					->findByCid($child['id']);
				if ($ac)
				{
					return ['data' => '分类下有文章!', 'code' => \Common::CODE_ERROR];
				}
				$cat = $this->find($child['id']);
				$this->getEntityManager()->remove($cat);
			}
			$this->getEntityManager()->flush();
			return ['data' => '删除成功!', 'code' => \Common::CODE_OK];
	}

	public function addCategoryTree($pid, $name)
	{
		$cat = new Category();
		$cat->setPid($pid);
		$cat->setName($name);
		$cat->setInfo("");
		$cat->setDel(0);
		$cat->setCtime(time());
		$this->getEntityManager()->persist($cat);
		$this->getEntityManager()->flush();
		return ['data' => $cat->getId(), 'code' => \Common::CODE_OK];
	}

	public function getCategoryChilds($pid = 0)
	{
		$ret = [];
		$categories = $this->findAll();
		foreach ($categories as $key => $category)
		{
			$category = $this->object2arr($category);
			if ($category['pid'] == $pid)
			{
				$ret[] = $category;
			}
		}
		return $ret;
	}

	public function getCategoryChilds_cascad($pid = 0)
	{
		$categories = $this->findAll();
		$break = [];
		foreach ($categories as $key => $category)
		{
			$category = $this->object2arr($category);
			if ($category['pid'] == $pid)
			{
				$break[] = $category;
			}
			$categories[$key] = $category;
		}
		$childs = $break;
		$tmp = [];
		{
			while (true)
			{
				if (count($break) == 0) break;
				foreach ($break as $b)
				{
					foreach ($categories as $category)
					{
						if ($category['pid'] == $b['id'])
						{
							$tmp[] = $category;
						}
					}
				}

				$childs = array_merge($childs, $tmp);
				$break = $tmp;
				$tmp = [];
			}
		}
		return $childs;
	}

	public function getCategoryParents($cid = 0)
	{
		$trail = [];
		$cat = $this->findById($cid);
		if (!$cat) { return $trail; }

		$trail[] = $this->object2arr($cat[0]);

		while ($cat[0]->getPid() != 0)
		{
			$cat = $this->findById($cat[0]->getPid());
			$trail[] = $this->object2arr($cat[0]);
		}
		return $trail;
	}
}
