<?php

namespace Yaf\Model\Repository;

use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Yaf\Model\Entities\Goods;
use Yaf\Model\Entities\GoodCategory;
use Yaf\Model\Entities\Category;
use Yaf\Model\Entities\GoodsImg;
use Yaf\Model\Entities\SendTimes;
use Yaf\Model\Entities\UserPrice;

/**
 * GoodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsRepository extends BaseRepository
{

    public function checkProductName($name, $id)
    {
        $i = 0;
        $good = $this->findByProductName($name);
        if ($good && $id)
        {
            foreach ($good as $g)
            {
                if (($good[0]->getId() != $id))
                {
                    $i++;
                }
            }
            return  $i > 0 ? false : true;
        }
        return $good ? false : true;
    }
    /**
     * 获得文章简介列表
     * @param array $where 默认无条件 格式 ["字段名" => "值", "ctime" => '16546457']
     * @param int $page 默认 1
     * @param int $limit 默认10
     * @param array $sort 默认无排序
     * @return Array
     */
    public function getGoodsIntroList($where = [], $page = 1, $limit = 10, $sort = [] )
    {

        $con = $this->getEntityManager()->getConnection();
        $sql = "select a.*, d.name  as cname, IFNULL(c.send_times, 0) as send_times, IFNULL(e.user_price, 0) as other_price from goods a
    	           left join good_category b on a.id = b.gid
                   left join send_times c on a.id = c.gid and c.uid = '".$_SESSION['user']."'
    	           left join category d on b.cid = d.id
                   left join user_price e on a.id = e.gid and e.uid = '".$_SESSION['user']."'
                   where ";

        $wheres[] = 'a.if_valid = 1';

        if ($where['search'])
        {
            $cat_repo = $this->_em->getRepository('Yaf\Model\Entities\Category');
            $childs = $cat_repo->getCategoryChilds_cascad($where['category']);
            $childs = array_column($childs, 'id');
            $childs[] = $where['category'];
            $wheres[] = '(d.name like "%'.$where['search'].'%" or a.product_name like "%'.$where['search'].'%") ';

        }
        if ($where['category'])
        {
        	$cat_repo = $this->_em->getRepository('Yaf\Model\Entities\Category');
        	$childs = $cat_repo->getCategoryChilds_cascad($where['category']);
        	$childs = array_column($childs, 'id');
        	$childs[] = $where['category'];
        	$wheres[] = 'b.cid in ('.implode(',', $childs).')';

        }
        if ($where['product_name'])
        {
            $wheres[] = 'a.product_name like "%'.$where['product_name'].'%"';
        }
        if ($where['brand'])
        {
            $wheres[] = 'a.brand like "%'.$where['brand'].'%"';
        }
        if ($where['creator'])
        {
            $wheres[] = 'a.creator like "%'.$where['creator'].'%"';
        }
        if ($where['send_times'])
        {
            $wheres[] = 'send_times <= '.$where['send_times'] . ' or send_times is null';
        }
        if ($where['low'])
        {
            $wheres[] = 'a.price >= ' . $where['low'];
        }
        if ($where['high'])
        {
            $wheres[] = 'a.price <= ' . $where['high'];
        }

        if ($where['cname'])
        {
            $wheres[] = 'd.name like "%'.$where['cname'].'%"';
        }

        foreach ($sort as $k => $v)
        {
            $sorts[] = $k. ' ' . $v;
        }

        $limits = ' limit ' . ($page)*$limit . ',' . $limit;

        if ($wheres)
        {
            $sql = $sql . implode(' and ', $wheres);
        }

        if ($sorts)
        {
            $sql = $sql. ' order by ' . implode(',', $sorts);
        }

        $goods = $con->fetchAll($sql);
        $total = count($goods);
        $sql = $sql . $limits;
        $goods = $con->fetchAll($sql);
        foreach ($goods as &$item)
        {
            $sql = "select img_path from goods_img
    	           where gid = " . $item['id'] . " and if_valid = 1";
            $images = $con->fetchAll($sql);
            $item['images'] = $images;
        }

        $ret = ['data' => $goods, 'total' => $total];
        return $ret;
    }

    public function getGoodById($id)
    {
		$con = $this->getEntityManager()->getConnection();

    	$sql = "select a.*, d.name  as cname, c.send_times , c.last_send_time, e.user_price as other_price from goods a
    	           left join good_category b on a.id = b.gid
    	           left join send_times c on c.gid = a.id and c.uid = '".$_SESSION['user']."'
    	           left join category d on b.cid = d.id
	               left join user_price e on a.id = e.gid and e.uid = '".$_SESSION['user']."'
    	           where a.id = " . $id;
    	$good = $con->fetchAssoc($sql);
    	$sql = "select img_path from goods_img
    	           where gid = " . $id . " and if_valid = 1";
    	$images = $con->fetchAll($sql);
    	$good['images'] = $images;
    	return $good;
    }

    public function addGood($params)
    {
    	$good = new Goods();
    	$good->setBrand($params['brand']);
    	$good->setProductName($params['product_name']);
    	$good->setAdCopy($params['ad_copy']);
    	$good->setCreator($params['creator']);
    	$good->setCtime(time());
    	$good->setPrice($params['price']);
    	$good->setDescription($params['description']);
    	$good->setSuggestedPrice($params['suggested_price']);
        $good->setIfValid((int)$params['if_valid']);
        $good->setSpecification("");
        $good->setUpdator("");
        $good->setUtime("");
        $this->getEntityManager()->persist($good);
        $this->getEntityManager()->flush();

        $ac = new GoodCategory($good);
    	$ac->setGid($good->getId());
    	$ac->setCid($params['category']);
    	$ac->setCtime(time());
    	$this->getEntityManager()->persist($ac);

    	$up = new UserPrice();
    	$up->setGid($good->getId());
    	$up->setUid($_SESSION['user']);
    	$up->setUserPrice($params['other_price']);
    	$this->getEntityManager()->persist($up);

    	//$good->setOtherPrice($params['other_price']);

    	foreach ($params['images'] as $image)
    	{
    	    $img = new GoodsImg();
    	    $img->setGid($good->getId());
    	    $img->setIfValid(1);
    	    $img->setImgPath($image['url']);
    	    $img->setMd5("");
    	    $this->getEntityManager()->persist($img);

    	}
    	//$this->getEntityManager()->persist($c);
    	$this->getEntityManager()->flush();


    	return [
    			'code' => 1,
    			'message' => '成功!'
    	];
    }

    public function updateGood($id, $params)
    {
    	$good = $this->getEntityManager()->find('Yaf\Model\Entities\Goods', $id);
    	$good->setBrand($params['brand']);
    	$good->setProductName($params['product_name']);
    	$good->setAdCopy($params['ad_copy']);
    	$good->setPrice($params['price']);
    	$good->setDescription($params['description']);
    	$good->setSuggestedPrice($params['suggested_price']);
        $good->setIfValid((int)$params['if_valid']);
        $good->setSpecification("");
        $good->setUpdator($params['creator']);
        $good->setUtime(time());
        $this->getEntityManager()->persist($good);

    	$category = $this->getEntityManager()->getRepository('Yaf\Model\Entities\GoodCategory')
                         ->findOneBy(['gid' => $id]);
    	$category->setCid($params['category']);
    	$this->getEntityManager()->persist($category);


    	$uprice = $this->getEntityManager()->getRepository('Yaf\Model\Entities\UserPrice')
    	               ->findOneBy(['gid' => $id, 'uid' => $_SESSION['user']]);
    	if ($uprice)
    	{
    	    $uprice->setUserPrice($params['other_price']);
    	}else
    	{
    	    $uprice = new UserPrice();
    	    $uprice->setGid($id);
    	    $uprice->setUid($_SESSION['user']);
    	    $uprice->setUserPrice($params['other_price']);
    	}
    	$this->getEntityManager()->persist($uprice);
    	$this->getEntityManager()->flush();

    	$images = $this->getEntityManager()->getRepository('Yaf\Model\Entities\GoodsImg')
    	               ->findBy(['gid' => $id]);

    	foreach ($images as $image)
    	{
    	    $this->getEntityManager()->remove($image);
    	}

    	foreach ($params['images'] as $image)
    	{
    	    $img = new GoodsImg();
    	    $img->setGid($good->getId());
    	    $img->setIfValid(1);
    	    $img->setImgPath($image['url']);
    	    $img->setMd5("");
    	    $this->getEntityManager()->persist($img);
    	}

    	$this->getEntityManager()->flush();

    	return [
    			'code' => 1,
    			'message' => '成功!'
    	];
    }

    public function deleteGood($id)
    {
        $good = $this->getEntityManager()->find('Yaf\Model\Entities\Goods', $id);
        if ($good) $this->getEntityManager()->remove($good);


    	$category = $this->getEntityManager()->getRepository('Yaf\Model\Entities\GoodCategory')
                         ->findOneBy(['gid' => $id]);
    	if ($category) $this->getEntityManager()->remove($category);

    	$uprice = $this->getEntityManager()->getRepository('Yaf\Model\Entities\UserPrice')
    	                   ->findOneBy(['gid' => $id, 'uid' => $_SESSION['user']]);
    	if ($uprice) $this->getEntityManager()->remove($uprice);

    	$times = $this->getEntityManager()->getRepository('Yaf\Model\Entities\SendTimes')
    	               ->findOneBy(['gid' => $id, 'uid' => $_SESSION['user']]);
    	if ($times) $this->getEntityManager()->remove($times);

    	$images = $this->getEntityManager()->getRepository('Yaf\Model\Entities\GoodsImg')
    	               ->findBy(['gid' => $id, 'ifValid' => 1]);

    	foreach ($images as $image)
    	{
    	   $image->setIfValid(0);
    	   $this->getEntityManager()->persist($image);
    	}

    	$this->getEntityManager()->flush();
    	return [
    			'code' => 1,
    			'message' => '成功!'
    	];
    }

    public function addSendTimes($gid)
    {
        $times = $this->getEntityManager()->getRepository('Yaf\Model\Entities\SendTimes')
                    ->findOneBy(['gid' => $gid, 'uid' => $_SESSION['user']]);
        if ($times)
        {
            $times->incSendTimes();
            $times->setLastSendTime(time());
        }else
        {
            $times = new SendTimes();
            $times->setGid($gid);
            $times->setUid($_SESSION['user']);
            $times->setLastSendTime(time());
            $times->setSendTimes(1);
        }
        $this->getEntityManager()->persist($times);
        $this->getEntityManager()->flush();
        return [
            'code' => 1,
            'message' => '成功!'
        ];
    }

}
