<?php

namespace Yaf\Model\Repository;

use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use Yaf\Model\Entities\Category;
/**
 * BlogCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SendTimesRepository extends BaseRepository
{

}
